### PR TITLE
fix page parse charset, if parse charset failed then use default utf8;

### PR DESCRIPTION
**Pull request by longcang**

### CODE REVIEW

**Comment by s17t** [comment]
Please always provide test with a PR.

**Comment by yasserg** [comment]
@s17t please revert this until an example is provided that shows this is needed.

**Comment by s17t** [comment]
@yasserg I added a test that shows a chance when found charset is not available in `Charset.forName(s)`. See https://github.com/yasserg/crawler4j/commit/bc69ad8bc2dc055b88af517b805ba8b57ae9c2a8, is that enough ?

**Comment by yasserg** [comment]
@s17t ok, I didn't see that.

**Pull request merged**
