### PR TITLE
Add shouldFollowLinksInPage(Page) method

### PR DESCRIPTION
**Pull request by bgoldowsky**
Permits implementation of policies that want to visit certain pages, but not look for and follow outgoing links in them.

Fixes https://github.com/yasserg/crawler4j/issues/129

### CODE REVIEW

**Comment by rzo1** [comment]
Why not use `shouldVisit` for this. In this method, we have the `Page` the URL was extracted from, so this logic can also implemented there...

**Comment by bgoldowsky** [comment]
@rzo1  I tried that, but (a) the code is more convoluted and hard to understand compared to splitting this test out into a separate method, (b) it is less efficient since the links are extracted, enqueued, and only later discarded.

Things get especially tricky in the case of redirects - you would have to somehow trace back through the chain or redirects to determine if you should have been following this link or not.  Much easier to prune the branch before it grows.

**Comment by rzo1** [comment]
I agree with your argumentation. I asked before @s17t  or someone else asks for the potential benefits  ;) - however, you should resolve the merge conflicts.

**Comment by bgoldowsky** [comment]
Merged in latest changes from master, resolving merge conflicts.
However, it's showing changes in .idea/compiler.xml -- I think this should be in .gitignore, it's automatically updated by the IDE.   Probably the whole .idea directory should be git ignored.

**Comment by s17t** [comment]
@rzo1, yes I agree with patch and with the use case.

**Pull request merged**
