### PR TITLE
Introduce tests from Diffblue Deeptest

### PR DESCRIPTION
**Pull request by JohnBergqvist**
The test cases contained in this PR were automatically generated by [Diffblue](http://www.diffblue.com)'s [Deeptest](http://www.diffblue.com/papers/overview.pdf) software.

Please feel free to merge them into your repository.

We would be delighted with any feedback you have on these tests.

### CODE REVIEW

**Comment by JohnBergqvist** [comment]
@yasserg Hello, 

May I ask why you rejected the PR?

**Comment by s17t** [comment]
@JohnBergqvist I m not against the merge but these are machine generated sources. They should play nice with maven lifecycles and not pollute the `/src/test/` space. 

Do you have a maven plugin of your library ?

**Comment by JohnBergqvist** [comment]
@s17t Hi,

Many thanks for you feedback. Are you saying you'd like tests for these methods to be written using Groovy?

**Comment by pgalbraith** [comment]
Hey John, I'm intrigued by what you group is doing, but can you formulate a real-world example of something that the test will catch?

**Pull request closed without merging**
