### PR TITLE
Create handler for 3xx pages

### PR DESCRIPTION
**Pull request by JCotton1123**
Add support for customizing handling of 3xx pages.

### CODE REVIEW

**Comment by s17t** [comment]
Thank you. Would mind to add some tests ? Looks at WebCrawlerTest and PageFetcherHtmlTest to see how to implement some test with wiremock.

**Comment by JCotton1123** [comment]
Can you add some documentation to the README on how to execute the tests and if there are additional requirements? I see that that WebCrawlerTest is implemented in Groovy.

**Comment by JCotton1123** [comment]
Nvmd. I see now that its just `mvn test`.

**Comment by JCotton1123** [comment]
I am kind of at a loss on how to test this appropriately.

**Pull request merged**
