### PR TITLE
Textual content parsing of HTML doesn't have enough spaces between tags.

### PR DESCRIPTION
**Pull request by cmacdonald**
This patch (with unit test) appends spaces to textual content parsing of HTML

### CODE REVIEW

**Comment by Chaiavi** [comment]
Can you help me understand please.

Using your unit tests, what will go wrong before your changes ?

**Comment by cmacdonald** [comment]
Some words that should be separated by spaces were not. e.g. "Hello theremr" instead of "Hello there mr" in test2ParaInBody

**Comment by Chaiavi** [comment]
Very nice


This one can be merged also

**Comment by yasserg** [comment]
Merged

**Pull request closed without merging**
