### PR TITLE
Add type safety to custom data

### PR DESCRIPTION
**Pull request by janstenpickle**
- WebCrawler and CrawlController can now be instantiated with a type for custom data used for configuring the crawler

### CODE REVIEW

**Comment by yasserg** [comment]
Most of the users don't use the custom data. But if we make this change, they will have to always specify the type which is not interesting. So, I prefer not to integrate this pull request.

**Comment by janstenpickle** [comment]
If you don't specify type it will default to `Object` so it won't break any existing usages of custom data.

**Comment by yasserg** [comment]
They would still get annoying warnings and it isn't a good programming practice.

**Comment by janstenpickle** [comment]
Are you suggesting that it isn't good programming practice to recommend type safety!?

**Comment by janstenpickle** [comment]
FYI you currently get annoying warnings about unchecked casts from object. This stackoverflow thread discusses how to resolve them: http://stackoverflow.com/questions/509076/how-do-i-address-unchecked-cast-warnings. In summary _do not do an unchecked cast if you can avoid it_, you should use generics (as I have done), more info here: https://docs.oracle.com/javase/tutorial/java/generics/why.html (note that generics were introduced in J2SE 5.0). 

I would have liked to think that keeping to established best practice (over what might be a very minor inconvenience to the users) should be a priority in a popular project like this. After all compiler warnings are there for a reason, either way produces them, at least the way I have proposed promotes best practice.

I, and I'm sure the rest of your users, really appreciate the work that you have done thus far with the project so please don't take my comments as a slight - I'm trying to help. Placing the source code on github implies that you wish to collaborate with the collective wisdom of the Java community, if you refuse to make reasoned arguments about potential improvements you contradict that implication. (Simply saying that possibly inconveniencing users should trump best practice, is in my opinion, not a reasoned argument).

**Comment by yasserg** [comment]
Thanks for your comments. What I was referring as not being a good programming practice is to have a class that has a template parameter which the majority of the users do not care about and then say that since it defaults to Object it won't break things. And, I was referring to warnings they would get.

In this specific case, of course adding type safety is an improvement but I don't think that this should be a template parameter of CrawlController and WebCrawler. Let me think about this more and see how we can do this better.

**Comment by janstenpickle** [comment]
Thanks for coming back to me on this, you're right it probably shouldn't be a template parameter of CrawlController and WebCrawler, maybe it would be better if the custom data were relocated to CrawlConfig. However this would be a breaking change for most users, maybe a deprecated flag on the old custom data and a new custom data in crawl config that is type safe?

**Comment by janstenpickle** [comment]
That said there will still have to be template parameter on CrawlController and WebCrawler so the custom data can be set and accessed properly in the crawler.

**Pull request closed without merging**
